name = "MatrixProductStates"
uuid = "d2b9b0d9-0b99-44d1-9ba5-49f6360db25a"
authors = ["Adam Smith <adam.smith.home@ntlworld.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
